# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Always restore open sites when qutebrowser is reopened.
# Type: Bool
c.auto_save.session = True

# The directory to save downloads to. If unset, a sensible os-specific
# default is used.
# Type: Directory
c.downloads.location.directory = '~/downloads'

# Bindings for normal mode
config.bind('<ctrl+pgdown>', 'tab-prev')
config.bind('<ctrl+pgup>', 'tab-focus')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-focus')