[theme]
theme = "semi-native"

[icons]
icons = "awesome5"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:80){ $marks.str(max_w:80)|} | "
short = " $title.str(max_w:20){ $marks.str(max_w:20)|} | "

[[block]]
block = "net" 
format_alt = " $icon {$signal_strength $ssid $frequency|Wired} via $device "
interval = 5
[block.format]
full = " $icon {$signal_strength $ssid @$ip|Wired @$ip} $graph_down "
short = " $icon {$ssid|Wired} "

[[block]]
block = "memory"
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
[block.format]
full = " $icon $path $available "
short = " $path $available "

[[block]]
block = "disk_space"
path = "~"
[block.format]
full = " $icon ~ $available "
short = " ~ $available "

[[block]]
block = "cpu"
interval = 5
[block.format]
full = " $icon $barchart $utilization $frequency "
short = " $icon $utilization "

[[block]]
block = "load"
interval = 5
format = " $icon $1m.eng(w:4) "

[[block]]
block = "sound"
format = " $icon {$volume.eng(w:3) |} "

[[block]]
block = "battery"
driver = "upower"
[block.format]
full = " $icon $percentage $time "
short = " $icon $percentage "

[[block]]
block = "time"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %T %z') " 
short = " $icon $timestamp.datetime(f:'%Y-%m-%d %T') "
