#!/usr/bin/env bash

#setup xdg variables
mkdir -p "$HOME"/.{config,cache,local/share}
XDG_DATA_HOME="$HOME/.local/share"
XDG_DATA_DIRS="/usr/local/share:/usr/share"
XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"

export XDG_RUNTIME_DIR XDG_DATA_{HOME,DIRS} XDG_{CONFIG,CACHE}_HOME

# ---------- Wayland -------------
#setup variables
QT_WAYLAND_FORCE_DPI=physical
GDK_BACKEND=wayland
WLR_RENDERER=vulkan
QT_QPA_PLATFORM=wayland-egl
CLUTTER_BACKEND=wayland
SDL_VIDEODRIVER=wayland

export QT_WAYLAND_FORCE_DPI GDK_BACKEND WLR_RENDERER QT_QPA_PLATFORM CLUTTER_BACKEND SDL_VIDEODRIVER

dbus-run-session -- sway
